### ISSUE TITLE
Revisión de proyecto

### ISSUE THREAD

**Issue by CarlosRubioTNM** [papery2129/Empresa#7]
Buen trabajo, jóvenes.

Les dejo un par de puntos a modificar para que repasen el concepto de Issues y branches.

- Coloquen el eslogan de la empresa.
- Modifiquen las tarjetas de los integrantes para que todas tengan el mismo tamaño.

Asignen a un colaborador y un label para el issue, creen una rama donde arreglen esos 2 puntos y realicen un pull request para combinar con la rama principal.

Al terminar, respondan en este issue etiquetándome para revisarlo.

Saludos.

**Comment by YesyRod13** [comment]
@CarlosRubioTNM ya fueron aplicados los cambios
